name: Update Changelog

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  update_changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write  # Needed for pushing changes
      pull-requests: read
    outputs:
      changelog_check_name: ${{ steps.get_outputs.outputs.changelog_check_name }}
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Information
        run: |
          echo "### Workflow Debug Information" >> $GITHUB_STEP_SUMMARY
          echo "- PR Title: ${{ github.event.pull_request.title }}" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: ${{ github.head_ref }}" >> $GITHUB_STEP_SUMMARY
          echo "- Triggered by: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY

      - name: Verify Required Files
        id: verify_files
        run: |
          echo "### File Verification" >> $GITHUB_STEP_SUMMARY

          # Check for README.md
          if [ -f "README.md" ]; then
            echo "✅ README.md found" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ README.md not found" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

          # Check for CHANGELOG.md
          if [ -f "CHANGELOG.md" ]; then
            echo "✅ CHANGELOG.md found" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ CHANGELOG.md not found" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install changelog dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub tenacity

      - name: Run Update Changelog Script
        id: update_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### File Update Status" >> $GITHUB_STEP_SUMMARY

          # Store the original SHA before any changes
          echo "original_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

          git checkout ${{ github.head_ref }} || exit 1


          # Run the script and capture its exit code
          python .github/scripts/update_changelog.py
          SCRIPT_EXIT=$?

          if [ $SCRIPT_EXIT -eq 0 ]; then
            # Check if there are changes to commit
            if [ -n "$(git status --porcelain)" ]; then
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add README.md CHANGELOG.md
              git commit -m "chore(version): Bump to $(grep -oP '\*\*Version = \K[0-9.]+(?=\*\*)' README.md)"
              git push origin HEAD:${{ github.head_ref }}

              # Store the new SHA after commit
              echo "new_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
              echo "changes_made=true" >> $GITHUB_OUTPUT
              echo "✅ Changelog and Readme files versions updated successfully" >> $GITHUB_STEP_SUMMARY
            else
              echo "changes_made=false" >> $GITHUB_OUTPUT
              echo "ℹ️ No changes needed" >> $GITHUB_STEP_SUMMARY
            fi

            echo "status=success" >> $GITHUB_OUTPUT
            echo "### Changelog Updated Successfully" >> $GITHUB_STEP_SUMMARY
            echo "Files updated: CHANGELOG.md and README.md" >> $GITHUB_STEP_SUMMARY

          elif [ $SCRIPT_EXIT -eq 2 ]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "changes_made=false" >> $GITHUB_OUTPUT
            echo "### Changelog Check Complete" >> $GITHUB_STEP_SUMMARY
            echo "No changes needed in changelog" >> $GITHUB_STEP_SUMMARY
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "### Changelog Update Failed" >> $GITHUB_STEP_SUMMARY
            echo "Error: Changelog update script failed with exit code $SCRIPT_EXIT" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Set Outputs
        id: get_outputs
        run: |
          echo "changelog_check_name=Update Changelog" >> $GITHUB_OUTPUT

      - name: Update PR Status
        if: steps.update_changelog.outputs.changes_made == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const newSha = '${{ steps.update_changelog.outputs.new_sha }}';
            const changelogName = '${{ steps.get_outputs.outputs.changelog_check_name }}';

            await github.rest.checks.create({
              owner,
              repo,
              name: changelogName,
              head_sha: newSha,
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'Documentation Updated',
                summary: 'Changelog and documentation were updated successfully'
              }
            });

      - name: Final Summary
        run: |
          echo "### Final Workflow Status" >> $GITHUB_STEP_SUMMARY
          echo "✅ Workflow completed successfully" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.update_changelog.outputs.changes_made }}" == "true" ]; then
            echo "- Changes were made and pushed" >> $GITHUB_STEP_SUMMARY
          else
            echo "- No changes were required" >> $GITHUB_STEP_SUMMARY
          fi
